### ISSUE TITLE
BrowserSync, device access

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo-browsersync#9]
_From @vedovato on July 2, 2015 17:17_

After install browsersync on hexo project, how can i access it on my phone at the same network? Tried to put my ip/4000 without success.

_Copied from original issue: hexojs/hexo#1366_

**Comment by leesei** [comment]
@vedovato, can you access your site at 4000 using `hexo server`?

**Comment by vedovato** [comment]
Only on my desktop. Mobile only display a not found page



Att,
*Andrei Vedovato Alves*
Desenvolvedor web

*www.andreivedovato.com <http://www.andreivedovato.com> *
*CL:* 19 99329-2025
*SK:* dvedovato

**Comment by leesei** [comment]
Then could it be that your mobile was not able to connect to your desktop
at all?

**Comment by Realetive** [comment]
I found this problem in some open WiFi hot-spots in cafe – routers blocked some ports, that the reason why devices cann't connect to your desktop. @leesei try to connect with other place or check that this port are open for remote connection.

**Comment by tcrowe** [comment]
Old issue, yes, but would be nice to close out.

In the `_config.yml` we can set the `host` and `port` so browsersync binds to it. Then it can be accessed across devices.

```yaml
browsersync:
  host: '192.168.1.101' # your IP on your network here
  port: 4001
```

There's no guarantee the wifi router will allow peer-to-peer on the same network. Also the tablet or phone device you want to test on has to allow it. There may be cross-origin problems because it's on another port.

Recommending close out old issues 👍
